---
- id: ocamlformat
  name: ocamlformat
  description: Format files using ocamlformat
  entry: opam exec ocamlformat -- -i
  language: system
  files: (\.ml|\.mli)$

- id: dunegen
  name: dunegen
  description: Generate dune files
  entry: opam exec dune -- build @gendune --auto-promote
  language: system
  files: (gen_dune.ml|dune|dune.inc)$
  pass_filenames: false

- id: duneopam
  name: duneopam
  description: Generate opam files
  entry: opam exec dune -- build
  language: system
  files: dune-project
  pass_filenames: false

