---
- id: dunefmt
  name: dunefmt
  description: Format files using dune
  entry: opam exec dune build @fmt --auto-promote
  language: system
  files: (\.ml|\.mli|dune|dune-project|dune.inc)$

- id: dunegen
  name: dunegen
  description: Generate dune files
  entry: opam exec dune build @gendune --auto-promote
  language: system
  files: (\.liq|\.ml|\.mli|dune|dune-project|dune.inc)$

- id: duneopam
  name: duneopam
  description: Generate opam files
  entry: opam exec dune build @install
  language: system
  files: dune-project$

